return {
  -- "nat-418/boole.nvim",
  "Susensio/boole.nvim", -- use fork to disable defaults
  branch = "feat-optional-defaults",
  event = { "BufReadPost", "BufNewFile" },
  opts = {
    mappings = {
      increment = "<C-a>",
      decrement = "<C-x>",
    },
    additions = {
      { "true", "false" },
      { "yes", "no" },
      { "on", "off" },
      {
        "monday",
        "tuesday",
        "wednesday",
        "thursday",
        "friday",
        "saturday",
        "sunday",
      },
      {
        "mon",
        "tue",
        "wed",
        "thu",
        "fri",
        "sat",
        "sun",
      },
      {
        "january",
        "february",
        "march",
        "april",
        "may",
        "june",
        "july",
        "august",
        "september",
        "october",
        "november",
        "december",
      },
      {
        "jan",
        "feb",
        "mar",
        "apr",
        "may",
        "jun",
        "jul",
        "aug",
        "sep",
        "oct",
        "nov",
        "dec",
      },
    },
    defaults = false,
  },
}
